services:
  postgres_analytics_db:
    image: 'postgres:latest'
    container_name: postgres_analytics_db
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5433:5432'
    networks:
      - honey_net

  analytic-service:
    build: .
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: ${DB_DATASOURCE}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      MYAPP_SECRET_KEY: ${MYAPP_SECRET_KEY}
    depends_on:
      - postgres_analytics_db
    networks:
      - honey_net

networks:
  honey_net:
    external: true
